### ISSUE TITLE
Update dependencies and Maven repositories

### ISSUE THREAD

**Issue by pgleeson** [LEMS/expr-parser#2]
I'm still getting errors related to retrieving the codehaus jars in the Travis tests: https://travis-ci.org/pgleeson/expr-parser/builds/183867152; https://travis-ci.org/pgleeson/org.lemsml.model/jobs/183867448

It would be good to update to latest stable version of these, consolidate the pom.xml & point to most stable location for jars.

**Comment by borismarin** [comment]
Interesting, given that
https://repo.maven.apache.org/maven2/org/codehaus/mojo/exec-maven-plugin/1.5.0/exec-maven-plugin-1.5.0.pom

seems to be live, and the [ojdk7 build](
https://travis-ci.org/pgleeson/expr-parser/jobs/183867153) has passed.

**Comment by pgleeson** [comment]
Will be fixed when #3 merged.
